name: Fuzzing on PR
on:
  pull_request_target:
    branches:
      - main
  
jobs:
  PrintInfo:
    if: |
      github.event.pull_request.base.ref == 'main' &&
      (github.event.pull_request.author_association == 'COLLABORATOR' ||
      github.event.pull_request.author_association == 'MEMBER' ||
      github.event.pull_request.author_association == 'OWNER')
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          echo "${{ toJSON(github.event) }}"
        
